### ISSUE TITLE
User-Agent

### ISSUE THREAD

**Issue by otobrglez** [databox/databox-java#1]
Hey!

In [this line here](https://github.com/databox/databox-java/blob/master/src/main/java/com/databox/sdk/Databox.java#L85) you are setting User-Agent for all requests that are passed to Databox. Can you please make sure it follows this pattern:

```
User-Agent: Databox/<your_client_version> (Java)
```

This is how other SDKs set it:
- [Ruby](https://github.com/databox/databox-ruby/blob/master/lib/databox/client.rb#L7)
- [Python](https://github.com/databox/databox-python/blob/master/databox/__init__.py#L60)

Thanks!

**Comment by umajeric** [comment]
Fixed.
